/*M!999999\- enable the sandbox mode */ 
-- MariaDB dump 10.19  Distrib 10.11.14-MariaDB, for debian-linux-gnu (x86_64)
--
-- Host: localhost    Database: asterisk
-- ------------------------------------------------------
-- Server version	10.11.14-MariaDB-0+deb12u2

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `userman_users`
--

DROP TABLE IF EXISTS `userman_users`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `userman_users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `auth` varchar(150) DEFAULT 'freepbx',
  `authid` varchar(750) DEFAULT NULL,
  `username` varchar(150) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `password` varchar(255) DEFAULT NULL,
  `default_extension` varchar(45) NOT NULL DEFAULT 'none',
  `primary_group` int(11) DEFAULT NULL,
  `permissions` longblob DEFAULT NULL,
  `fname` varchar(100) DEFAULT NULL,
  `lname` varchar(100) DEFAULT NULL,
  `displayname` varchar(200) DEFAULT NULL,
  `title` varchar(100) DEFAULT NULL,
  `company` varchar(100) DEFAULT NULL,
  `department` varchar(100) DEFAULT NULL,
  `language` varchar(100) DEFAULT NULL,
  `timezone` varchar(100) DEFAULT NULL,
  `dateformat` varchar(100) DEFAULT NULL,
  `timeformat` varchar(100) DEFAULT NULL,
  `datetimeformat` varchar(100) DEFAULT NULL,
  `email` longtext DEFAULT NULL,
  `cell` varchar(100) DEFAULT NULL,
  `work` varchar(100) DEFAULT NULL,
  `home` varchar(100) DEFAULT NULL,
  `fax` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username_UNIQUE` (`username`,`auth`)
) ENGINE=InnoDB AUTO_INCREMENT=64 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `userman_users`
--

LOCK TABLES `userman_users` WRITE;
/*!40000 ALTER TABLE `userman_users` DISABLE KEYS */;
INSERT INTO `userman_users` VALUES
(1,'1',NULL,'101','Autogenerated user on new device creation','$2a$08$caom2ottxNb8G1CsXRW54uRa7g/cjXK4GXnyNlo0lAySVuKyt4kS6','101',1,NULL,NULL,NULL,'MR. Youssef',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(2,'1',NULL,'102','Autogenerated user on new device creation','$2a$08$caom2ottxNb8G1CsXRW54uRa7g/cjXK4GXnyNlo0lAySVuKyt4kS6','102',1,NULL,NULL,NULL,'MS. Elham',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(3,'1',NULL,'103','Autogenerated user on new device creation','$2a$08$caom2ottxNb8G1CsXRW54uRa7g/cjXK4GXnyNlo0lAySVuKyt4kS6','103',1,NULL,NULL,NULL,'MS. Monica',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(4,'1',NULL,'104','Autogenerated user on new device creation','$2a$08$caom2ottxNb8G1CsXRW54uRa7g/cjXK4GXnyNlo0lAySVuKyt4kS6','104',1,NULL,NULL,NULL,'MS. Christina',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(5,'1',NULL,'200','Autogenerated user on new device creation','$2a$08$caom2ottxNb8G1CsXRW54uRa7g/cjXK4GXnyNlo0lAySVuKyt4kS6','200',1,NULL,NULL,NULL,'Alex Sales',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(6,'1',NULL,'201','Autogenerated user on new device creation','$2a$08$caom2ottxNb8G1CsXRW54uRa7g/cjXK4GXnyNlo0lAySVuKyt4kS6','201',1,NULL,NULL,NULL,'Alex Sales 1 (Olivia)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(7,'1',NULL,'202','Autogenerated user on new device creation','$2a$08$caom2ottxNb8G1CsXRW54uRa7g/cjXK4GXnyNlo0lAySVuKyt4kS6','202',1,NULL,NULL,NULL,'Alex Sales 2 (Avrosina)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(8,'1',NULL,'203','Autogenerated user on new device creation','$2a$08$caom2ottxNb8G1CsXRW54uRa7g/cjXK4GXnyNlo0lAySVuKyt4kS6','203',1,NULL,NULL,NULL,'Alex Sales 3 (Mirana)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(9,'1',NULL,'204','Autogenerated user on new device creation','$2a$08$caom2ottxNb8G1CsXRW54uRa7g/cjXK4GXnyNlo0lAySVuKyt4kS6','204',1,NULL,NULL,NULL,'Alex Sales (Silvia)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(10,'1',NULL,'205','Autogenerated user on new device creation','$2a$08$caom2ottxNb8G1CsXRW54uRa7g/cjXK4GXnyNlo0lAySVuKyt4kS6','205',1,NULL,NULL,NULL,'Cairo Sales',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(11,'1',NULL,'206','Autogenerated user on new device creation','$2a$08$caom2ottxNb8G1CsXRW54uRa7g/cjXK4GXnyNlo0lAySVuKyt4kS6','206',1,NULL,NULL,NULL,'Cairo Sales 1 (Marina)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(12,'1',NULL,'207','Autogenerated user on new device creation','$2a$08$caom2ottxNb8G1CsXRW54uRa7g/cjXK4GXnyNlo0lAySVuKyt4kS6','207',1,NULL,NULL,NULL,'Cairo Sales 2 (Marim W)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(13,'1',NULL,'208','Autogenerated user on new device creation','$2a$08$caom2ottxNb8G1CsXRW54uRa7g/cjXK4GXnyNlo0lAySVuKyt4kS6','208',1,NULL,NULL,NULL,'Cairo Sales 3 (Marim W)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(14,'1',NULL,'209','Autogenerated user on new device creation','$2a$08$caom2ottxNb8G1CsXRW54uRa7g/cjXK4GXnyNlo0lAySVuKyt4kS6','209',1,NULL,NULL,NULL,'Alex Sales (Nagy)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(15,'1',NULL,'301','Autogenerated user on new device creation','$2a$08$caom2ottxNb8G1CsXRW54uRa7g/cjXK4GXnyNlo0lAySVuKyt4kS6','301',1,NULL,NULL,NULL,'MS. Marian',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(16,'1',NULL,'302','Autogenerated user on new device creation','$2a$08$caom2ottxNb8G1CsXRW54uRa7g/cjXK4GXnyNlo0lAySVuKyt4kS6','302',1,NULL,NULL,NULL,'MS. Maha',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(17,'1',NULL,'303','Autogenerated user on new device creation','$2a$08$caom2ottxNb8G1CsXRW54uRa7g/cjXK4GXnyNlo0lAySVuKyt4kS6','303',1,NULL,NULL,NULL,'MS. Karen Akrm',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(18,'1',NULL,'304','Autogenerated user on new device creation','$2a$08$caom2ottxNb8G1CsXRW54uRa7g/cjXK4GXnyNlo0lAySVuKyt4kS6','304',1,NULL,NULL,NULL,'MS. Caroline Hany',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(19,'1',NULL,'305','Autogenerated user on new device creation','$2a$08$caom2ottxNb8G1CsXRW54uRa7g/cjXK4GXnyNlo0lAySVuKyt4kS6','305',1,NULL,NULL,NULL,'MS. Ojonei',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(20,'1',NULL,'306','Autogenerated user on new device creation','$2a$08$caom2ottxNb8G1CsXRW54uRa7g/cjXK4GXnyNlo0lAySVuKyt4kS6','306',1,NULL,NULL,NULL,'Karla',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(21,'1',NULL,'401','Autogenerated user on new device creation','$2a$08$caom2ottxNb8G1CsXRW54uRa7g/cjXK4GXnyNlo0lAySVuKyt4kS6','401',1,NULL,NULL,NULL,'Ms. Mariz Saber',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(22,'1',NULL,'402','Autogenerated user on new device creation','$2a$08$caom2ottxNb8G1CsXRW54uRa7g/cjXK4GXnyNlo0lAySVuKyt4kS6','402',1,NULL,NULL,NULL,'Ms. Amalide',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(23,'1',NULL,'403','Autogenerated user on new device creation','$2a$08$caom2ottxNb8G1CsXRW54uRa7g/cjXK4GXnyNlo0lAySVuKyt4kS6','403',1,NULL,NULL,NULL,'Ms. Amy',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(24,'1',NULL,'501','Autogenerated user on new device creation','$2a$08$caom2ottxNb8G1CsXRW54uRa7g/cjXK4GXnyNlo0lAySVuKyt4kS6','501',1,NULL,NULL,NULL,'Voicemail InWorkTime',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(25,'1',NULL,'502','Autogenerated user on new device creation','$2a$08$caom2ottxNb8G1CsXRW54uRa7g/cjXK4GXnyNlo0lAySVuKyt4kS6','502',1,NULL,NULL,NULL,'Voicemail OutWorkTime',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(26,'1',NULL,'503','Autogenerated user on new device creation','$2a$08$caom2ottxNb8G1CsXRW54uRa7g/cjXK4GXnyNlo0lAySVuKyt4kS6','503',1,NULL,NULL,NULL,'Voicemail YoussefShakwa',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(27,'1',NULL,'504','Autogenerated user on new device creation','$2a$08$caom2ottxNb8G1CsXRW54uRa7g/cjXK4GXnyNlo0lAySVuKyt4kS6','504',1,NULL,NULL,NULL,'FilesVoicemail',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(28,'1',NULL,'505','Autogenerated user on new device creation','$2a$08$caom2ottxNb8G1CsXRW54uRa7g/cjXK4GXnyNlo0lAySVuKyt4kS6','505',1,NULL,NULL,NULL,'Shakwa',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(29,'1',NULL,'600','Autogenerated user on new device creation','$2a$08$caom2ottxNb8G1CsXRW54uRa7g/cjXK4GXnyNlo0lAySVuKyt4kS6','600',1,NULL,NULL,NULL,'Extension 600',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(30,'1',NULL,'601','Autogenerated user on new device creation','$2a$08$caom2ottxNb8G1CsXRW54uRa7g/cjXK4GXnyNlo0lAySVuKyt4kS6','601',1,NULL,NULL,NULL,'Extension 601',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(31,'1',NULL,'602','Autogenerated user on new device creation','$2a$08$caom2ottxNb8G1CsXRW54uRa7g/cjXK4GXnyNlo0lAySVuKyt4kS6','602',1,NULL,NULL,NULL,'Extension 602',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(32,'1',NULL,'603','Autogenerated user on new device creation','$2a$08$caom2ottxNb8G1CsXRW54uRa7g/cjXK4GXnyNlo0lAySVuKyt4kS6','603',1,NULL,NULL,NULL,'Extension 603',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(33,'1',NULL,'604','Autogenerated user on new device creation','$2a$08$caom2ottxNb8G1CsXRW54uRa7g/cjXK4GXnyNlo0lAySVuKyt4kS6','604',1,NULL,NULL,NULL,'Extension 604',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(34,'1',NULL,'605','Autogenerated user on new device creation','$2a$08$caom2ottxNb8G1CsXRW54uRa7g/cjXK4GXnyNlo0lAySVuKyt4kS6','605',1,NULL,NULL,NULL,'Extension 605',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(35,'1',NULL,'606','Autogenerated user on new device creation','$2a$08$caom2ottxNb8G1CsXRW54uRa7g/cjXK4GXnyNlo0lAySVuKyt4kS6','606',1,NULL,NULL,NULL,'Extension 606',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(36,'1',NULL,'607','Autogenerated user on new device creation','$2a$08$caom2ottxNb8G1CsXRW54uRa7g/cjXK4GXnyNlo0lAySVuKyt4kS6','607',1,NULL,NULL,NULL,'Extension 607',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(37,'1',NULL,'608','Autogenerated user on new device creation','$2a$08$caom2ottxNb8G1CsXRW54uRa7g/cjXK4GXnyNlo0lAySVuKyt4kS6','608',1,NULL,NULL,NULL,'Extension 608',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(38,'1',NULL,'609','Autogenerated user on new device creation','$2a$08$caom2ottxNb8G1CsXRW54uRa7g/cjXK4GXnyNlo0lAySVuKyt4kS6','609',1,NULL,NULL,NULL,'Extension 609',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(39,'1',NULL,'610','Autogenerated user on new device creation','$2a$08$caom2ottxNb8G1CsXRW54uRa7g/cjXK4GXnyNlo0lAySVuKyt4kS6','610',1,NULL,NULL,NULL,'Extension 610',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(40,'1',NULL,'999','Autogenerated user on new device creation','$2a$08$caom2ottxNb8G1CsXRW54uRa7g/cjXK4GXnyNlo0lAySVuKyt4kS6','999',1,NULL,NULL,NULL,'Test',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(41,'1',NULL,'1002','Autogenerated user on new device creation','$2a$08$caom2ottxNb8G1CsXRW54uRa7g/cjXK4GXnyNlo0lAySVuKyt4kS6','1002',1,NULL,NULL,NULL,'IT Micheal',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(42,'1',NULL,'5050','Autogenerated user on new device creation','$2a$08$caom2ottxNb8G1CsXRW54uRa7g/cjXK4GXnyNlo0lAySVuKyt4kS6','5050',1,NULL,NULL,NULL,'Malak Magdy Lawyer',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
/*!40000 ALTER TABLE `userman_users` ENABLE KEYS */;
UNLOCK TABLES;
/*!50003 SET @saved_cs_client      = @@character_set_client */ ;
/*!50003 SET @saved_cs_results     = @@character_set_results */ ;
/*!50003 SET @saved_col_connection = @@collation_connection */ ;
/*!50003 SET character_set_client  = utf8mb4 */ ;
/*!50003 SET character_set_results = utf8mb4 */ ;
/*!50003 SET collation_connection  = utf8mb4_general_ci */ ;
/*!50003 SET @saved_sql_mode       = @@sql_mode */ ;
/*!50003 SET sql_mode              = 'STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION' */ ;
DELIMITER ;;
/*!50003 CREATE*/ /*!50017 DEFINER=`freepbxuser`@`localhost`*/ /*!50003 TRIGGER srtapi_after_update_userman_users
			AFTER UPDATE ON userman_users
			FOR EACH ROW
			BEGIN
				DECLARE _new_first_name TEXT;
				DECLARE _new_last_name TEXT;

				SET _new_first_name = NEW.fname;
				SET _new_last_name = NEW.lname;

				-- Use displayname if the user does not have a first or last
				-- name set.
				IF ((_new_first_name IS NULL OR _new_first_name = '')
					AND (_new_last_name IS NULL OR _new_last_name = '')
					AND (NEW.displayname IS NOT NULL OR NEW.displayname != ''))
				THEN
					SET _new_first_name = NEW.displayname;
				END IF;

				IF (_new_first_name != OLD.fname
					OR _new_last_name != OLD.lname
					OR NEW.default_extension != OLD.default_extension
				) THEN
					UPDATE srtapi_chat_users
					SET    first_name = _new_first_name,
						   last_name = _new_last_name,
						   number = NEW.default_extension
					WHERE  user_id IN
					(
						-- Get the chat user associated with the updated userman_users account.
						SELECT user_id
						FROM   srtapi_chat_user_to_contact
						WHERE    account_id = NEW.id
					);
				END IF;
			END */;;
DELIMITER ;
/*!50003 SET sql_mode              = @saved_sql_mode */ ;
/*!50003 SET character_set_client  = @saved_cs_client */ ;
/*!50003 SET character_set_results = @saved_cs_results */ ;
/*!50003 SET collation_connection  = @saved_col_connection */ ;

--
-- Table structure for table `userman_groups`
--

DROP TABLE IF EXISTS `userman_groups`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `userman_groups` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `auth` varchar(150) DEFAULT 'freepbx',
  `authid` varchar(750) DEFAULT NULL,
  `groupname` varchar(150) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `language` varchar(100) DEFAULT NULL,
  `timezone` varchar(100) DEFAULT NULL,
  `dateformat` varchar(100) DEFAULT NULL,
  `timeformat` varchar(100) DEFAULT NULL,
  `datetimeformat` varchar(100) DEFAULT NULL,
  `priority` int(11) NOT NULL DEFAULT 5,
  `users` longblob DEFAULT NULL,
  `permissions` longblob DEFAULT NULL,
  `local` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `groupname_UNIQUE` (`groupname`,`auth`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `userman_groups`
--

LOCK TABLES `userman_groups` WRITE;
/*!40000 ALTER TABLE `userman_groups` DISABLE KEYS */;
INSERT INTO `userman_groups` VALUES
(1,'1',NULL,'All Users','This group was created on install and is automatically assigned to new users. This can be disabled in User Manager Settings',NULL,NULL,NULL,NULL,NULL,5,'null',NULL,0);
/*!40000 ALTER TABLE `userman_groups` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `userman_users_settings`
--

DROP TABLE IF EXISTS `userman_users_settings`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `userman_users_settings` (
  `uid` int(11) NOT NULL,
  `module` varchar(65) NOT NULL,
  `key` varchar(190) NOT NULL,
  `val` longblob NOT NULL,
  `type` varchar(16) DEFAULT NULL,
  UNIQUE KEY `index4` (`uid`,`module`,`key`),
  KEY `index2` (`uid`,`key`),
  KEY `index6` (`module`,`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `userman_users_settings`
--

LOCK TABLES `userman_users_settings` WRITE;
/*!40000 ALTER TABLE `userman_users_settings` DISABLE KEYS */;
INSERT INTO `userman_users_settings` VALUES
(1,'','assigned','[\"101\"]','json-arr'),
(1,'','groups','[\"1\"]','json-arr'),
(2,'','assigned','[\"102\"]','json-arr'),
(2,'','groups','[\"1\"]','json-arr'),
(3,'','assigned','[\"103\"]','json-arr'),
(3,'','groups','[\"1\"]','json-arr'),
(4,'','assigned','[\"104\"]','json-arr'),
(4,'','groups','[\"1\"]','json-arr'),
(5,'','assigned','[\"200\"]','json-arr'),
(5,'','groups','[\"1\"]','json-arr'),
(6,'','assigned','[\"201\"]','json-arr'),
(6,'','groups','[\"1\"]','json-arr'),
(7,'','assigned','[\"202\"]','json-arr'),
(7,'','groups','[\"1\"]','json-arr'),
(8,'','assigned','[\"203\"]','json-arr'),
(8,'','groups','[\"1\"]','json-arr'),
(9,'','assigned','[\"204\"]','json-arr'),
(9,'','groups','[\"1\"]','json-arr'),
(10,'','assigned','[\"205\"]','json-arr'),
(10,'','groups','[\"1\"]','json-arr'),
(11,'','assigned','[\"206\"]','json-arr'),
(11,'','groups','[\"1\"]','json-arr'),
(12,'','assigned','[\"207\"]','json-arr'),
(12,'','groups','[\"1\"]','json-arr'),
(13,'','assigned','[\"208\"]','json-arr'),
(13,'','groups','[\"1\"]','json-arr'),
(14,'','assigned','[\"209\"]','json-arr'),
(14,'','groups','[\"1\"]','json-arr'),
(15,'','assigned','[\"301\"]','json-arr'),
(15,'','groups','[\"1\"]','json-arr'),
(16,'','assigned','[\"302\"]','json-arr'),
(16,'','groups','[\"1\"]','json-arr'),
(17,'','assigned','[\"303\"]','json-arr'),
(17,'','groups','[\"1\"]','json-arr'),
(18,'','assigned','[\"304\"]','json-arr'),
(18,'','groups','[\"1\"]','json-arr'),
(19,'','assigned','[\"305\"]','json-arr'),
(19,'','groups','[\"1\"]','json-arr'),
(20,'','assigned','[\"306\"]','json-arr'),
(20,'','groups','[\"1\"]','json-arr'),
(21,'','assigned','[\"401\"]','json-arr'),
(21,'','groups','[\"1\"]','json-arr'),
(22,'','assigned','[\"402\"]','json-arr'),
(22,'','groups','[\"1\"]','json-arr'),
(23,'','assigned','[\"403\"]','json-arr'),
(23,'','groups','[\"1\"]','json-arr'),
(24,'','assigned','[\"501\"]','json-arr'),
(24,'','groups','[\"1\"]','json-arr'),
(25,'','assigned','[\"502\"]','json-arr'),
(25,'','groups','[\"1\"]','json-arr'),
(26,'','assigned','[\"503\"]','json-arr'),
(26,'','groups','[\"1\"]','json-arr'),
(27,'','assigned','[\"504\"]','json-arr'),
(27,'','groups','[\"1\"]','json-arr'),
(28,'','assigned','[\"505\"]','json-arr'),
(28,'','groups','[\"1\"]','json-arr'),
(29,'','assigned','[\"600\"]','json-arr'),
(29,'','groups','[\"1\"]','json-arr'),
(30,'','assigned','[\"601\"]','json-arr'),
(30,'','groups','[\"1\"]','json-arr'),
(31,'','assigned','[\"602\"]','json-arr'),
(31,'','groups','[\"1\"]','json-arr'),
(32,'','assigned','[\"603\"]','json-arr'),
(32,'','groups','[\"1\"]','json-arr'),
(33,'','assigned','[\"604\"]','json-arr'),
(33,'','groups','[\"1\"]','json-arr'),
(34,'','assigned','[\"605\"]','json-arr'),
(34,'','groups','[\"1\"]','json-arr'),
(35,'','assigned','[\"606\"]','json-arr'),
(35,'','groups','[\"1\"]','json-arr'),
(36,'','assigned','[\"607\"]','json-arr'),
(36,'','groups','[\"1\"]','json-arr'),
(37,'','assigned','[\"608\"]','json-arr'),
(37,'','groups','[\"1\"]','json-arr'),
(38,'','assigned','[\"609\"]','json-arr'),
(38,'','groups','[\"1\"]','json-arr'),
(39,'','assigned','[\"610\"]','json-arr'),
(39,'','groups','[\"1\"]','json-arr'),
(40,'','assigned','[\"999\"]','json-arr'),
(40,'','groups','[\"1\"]','json-arr'),
(41,'','assigned','[\"1002\"]','json-arr'),
(41,'','groups','[\"1\"]','json-arr'),
(42,'','assigned','[\"5050\"]','json-arr'),
(42,'','groups','[\"1\"]','json-arr');
/*!40000 ALTER TABLE `userman_users_settings` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2026-01-12  5:14:47
